/* compiled from: . */
/* /usr/include/dlfcn.h:57:NC */ extern void *dlopen (const char *, int);
/* /usr/include/dlfcn.h:61:NC */ extern int dlclose (void *);
/* /usr/include/dlfcn.h:65:NC */ extern void *dlsym (void *, const char *);
/* /usr/include/dlfcn.h:83:NC */ extern char *dlerror (void);
/* /usr/include/unistd.h:288:NC */ extern int access (const char *, int);
/* /usr/include/unistd.h:305:NC */ extern int faccessat (int, const char *, int, int);
/* /usr/include/unistd.h:335:NC */ extern __off_t lseek (int, __off_t, int);
/* /usr/include/unistd.h:354:NC */ extern int close (int);
/* /usr/include/unistd.h:361:NC */ extern ssize_t read (int, void *, size_t);
/* /usr/include/unistd.h:367:NC */ extern ssize_t write (int, const void *, size_t);
/* /usr/include/unistd.h:377:NC */ extern ssize_t pread (int, void *, size_t, __off_t);
/* /usr/include/unistd.h:385:NC */ extern ssize_t pwrite (int, const void *, size_t, __off_t);
/* /usr/include/unistd.h:418:NC */ extern int pipe (int *);
/* /usr/include/unistd.h:433:NC */ extern unsigned int alarm (unsigned int);
/* /usr/include/unistd.h:445:NC */ extern unsigned int sleep (unsigned int);
/* /usr/include/unistd.h:453:NC */ extern __useconds_t ualarm (__useconds_t, __useconds_t);
/* /usr/include/unistd.h:461:NC */ extern int usleep (__useconds_t);
/* /usr/include/unistd.h:470:NC */ extern int pause (void);
/* /usr/include/unistd.h:474:NC */ extern int chown (const char *, __uid_t, __gid_t);
/* /usr/include/unistd.h:479:NC */ extern int fchown (int, __uid_t, __gid_t);
/* /usr/include/unistd.h:484:NC */ extern int lchown (const char *, __uid_t, __gid_t);
/* /usr/include/unistd.h:492:NC */ extern int fchownat (int, const char *, __uid_t, __gid_t, int);
/* /usr/include/unistd.h:498:NC */ extern int chdir (const char *);
/* /usr/include/unistd.h:502:NC */ extern int fchdir (int);
/* /usr/include/unistd.h:512:NC */ extern char *getcwd (char *, size_t);
/* /usr/include/unistd.h:526:NC */ extern char *getwd (char *);
/* /usr/include/unistd.h:532:NC */ extern int dup (int);
/* /usr/include/unistd.h:535:NC */ extern int dup2 (int, int);
/* /usr/include/unistd.h:552:NC */ extern int execve (const char *, char *const *, char *const *);
/* /usr/include/unistd.h:558:NC */ extern int fexecve (int, char *const *, char *const *);
/* /usr/include/unistd.h:564:NC */ extern int execv (const char *, char *const *);
/* /usr/include/unistd.h:569:NC */ extern int execle (const char *, const char *, ...);
/* /usr/include/unistd.h:574:NC */ extern int execl (const char *, const char *, ...);
/* /usr/include/unistd.h:579:NC */ extern int execvp (const char *, char *const *);
/* /usr/include/unistd.h:585:NC */ extern int execlp (const char *, const char *, ...);
/* /usr/include/unistd.h:599:NC */ extern int nice (int);
/* /usr/include/unistd.h:604:NC */ extern void _exit (int);
/* /usr/include/unistd.h:613:NC */ extern long int pathconf (const char *, int);
/* /usr/include/unistd.h:617:NC */ extern long int fpathconf (int, int);
/* /usr/include/unistd.h:620:NC */ extern long int sysconf (int);
/* /usr/include/unistd.h:624:NC */ extern size_t confstr (int, char *, size_t);
/* /usr/include/unistd.h:629:NC */ extern __pid_t getpid (void);
/* /usr/include/unistd.h:632:NC */ extern __pid_t getppid (void);
/* /usr/include/unistd.h:637:NC */ extern __pid_t getpgrp (void);
/* /usr/include/unistd.h:647:NC */ extern __pid_t __getpgid (__pid_t);
/* /usr/include/unistd.h:649:NC */ extern __pid_t getpgid (__pid_t);
/* /usr/include/unistd.h:656:NC */ extern int setpgid (__pid_t, __pid_t);
/* /usr/include/unistd.h:673:NC */ extern int setpgrp (void);
/* /usr/include/unistd.h:690:NC */ extern __pid_t setsid (void);
/* /usr/include/unistd.h:694:NC */ extern __pid_t getsid (__pid_t);
/* /usr/include/unistd.h:698:NC */ extern __uid_t getuid (void);
/* /usr/include/unistd.h:701:NC */ extern __uid_t geteuid (void);
/* /usr/include/unistd.h:704:NC */ extern __gid_t getgid (void);
/* /usr/include/unistd.h:707:NC */ extern __gid_t getegid (void);
/* /usr/include/unistd.h:712:NC */ extern int getgroups (int, __gid_t *);
/* /usr/include/unistd.h:723:NC */ extern int setuid (__uid_t);
/* /usr/include/unistd.h:728:NC */ extern int setreuid (__uid_t, __uid_t);
/* /usr/include/unistd.h:733:NC */ extern int seteuid (__uid_t);
/* /usr/include/unistd.h:740:NC */ extern int setgid (__gid_t);
/* /usr/include/unistd.h:745:NC */ extern int setregid (__gid_t, __gid_t);
/* /usr/include/unistd.h:750:NC */ extern int setegid (__gid_t);
/* /usr/include/unistd.h:779:NC */ extern __pid_t fork (void);
/* /usr/include/unistd.h:787:NC */ extern __pid_t vfork (void);
/* /usr/include/unistd.h:793:NC */ extern char *ttyname (int);
/* /usr/include/unistd.h:797:NC */ extern int ttyname_r (int, char *, size_t);
/* /usr/include/unistd.h:802:NC */ extern int isatty (int);
/* /usr/include/unistd.h:808:NC */ extern int ttyslot (void);
/* /usr/include/unistd.h:813:NC */ extern int link (const char *, const char *);
/* /usr/include/unistd.h:819:NC */ extern int linkat (int, const char *, int, const char *, int);
/* /usr/include/unistd.h:826:NC */ extern int symlink (const char *, const char *);
/* /usr/include/unistd.h:832:NC */ extern ssize_t readlink (const char *, char *, size_t);
/* /usr/include/unistd.h:839:NC */ extern int symlinkat (const char *, int, const char *);
/* /usr/include/unistd.h:843:NC */ extern ssize_t readlinkat (int, const char *, char *, size_t);
/* /usr/include/unistd.h:849:NC */ extern int unlink (const char *);
/* /usr/include/unistd.h:853:NC */ extern int unlinkat (int, const char *, int);
/* /usr/include/unistd.h:858:NC */ extern int rmdir (const char *);
/* /usr/include/unistd.h:862:NC */ extern __pid_t tcgetpgrp (int);
/* /usr/include/unistd.h:865:NC */ extern int tcsetpgrp (int, __pid_t);
/* /usr/include/unistd.h:872:NC */ extern char *getlogin (void);
/* /usr/include/unistd.h:880:NC */ extern int getlogin_r (char *, size_t);
/* /usr/include/unistd.h:885:NC */ extern int setlogin (const char *);
/* /usr/include/getopt.h:152:NC */ extern int getopt (int, char *const *, const char *);
/* /usr/include/unistd.h:902:NC */ extern int gethostname (char *, size_t);
/* /usr/include/unistd.h:909:NC */ extern int sethostname (const char *, size_t);
/* /usr/include/unistd.h:914:NC */ extern int sethostid (long int);
/* /usr/include/unistd.h:920:NC */ extern int getdomainname (char *, size_t);
/* /usr/include/unistd.h:922:NC */ extern int setdomainname (const char *, size_t);
/* /usr/include/unistd.h:929:NC */ extern int vhangup (void);
/* /usr/include/unistd.h:932:NC */ extern int revoke (const char *);
/* /usr/include/unistd.h:940:NC */ extern int profil (short unsigned int *, size_t, size_t, unsigned int);
/* /usr/include/unistd.h:948:NC */ extern int acct (const char *);
/* /usr/include/unistd.h:952:NC */ extern char *getusershell (void);
/* /usr/include/unistd.h:953:NC */ extern void endusershell (void);
/* /usr/include/unistd.h:954:NC */ extern void setusershell (void);
/* /usr/include/unistd.h:960:NC */ extern int daemon (int, int);
/* /usr/include/unistd.h:967:NC */ extern int chroot (const char *);
/* /usr/include/unistd.h:971:NC */ extern char *getpass (const char *);
/* /usr/include/unistd.h:980:NC */ extern int fsync (int);
/* /usr/include/unistd.h:994:NC */ extern long int gethostid (void);
/* /usr/include/unistd.h:997:NC */ extern void sync (void);
/* /usr/include/unistd.h:1003:NC */ extern int getpagesize (void);
/* /usr/include/unistd.h:1008:NC */ extern int getdtablesize (void);
/* /usr/include/unistd.h:1018:NC */ extern int truncate (const char *, __off_t);
/* /usr/include/unistd.h:1040:NC */ extern int ftruncate (int, __off_t);
/* /usr/include/unistd.h:1061:NC */ extern int brk (void *);
/* /usr/include/unistd.h:1067:NC */ extern void *sbrk (intptr_t);
/* /usr/include/unistd.h:1082:NC */ extern long int syscall (long int, ...);
/* /usr/include/unistd.h:1105:NC */ extern int lockf (int, int, __off_t);
/* /usr/include/unistd.h:1136:NC */ extern int fdatasync (int);
/* /usr/include/unistd.h:1165:NC */ extern char *ctermid (char *);
/* /usr/include/stdlib.h:140:NC */ extern size_t __ctype_get_mb_cur_max (void);
/* /usr/include/stdlib.h:145:NC */ extern double atof (const char *);
/* /usr/include/stdlib.h:148:NC */ extern int atoi (const char *);
/* /usr/include/stdlib.h:151:NC */ extern long int atol (const char *);
/* /usr/include/stdlib.h:158:NC */ extern long long int atoll (const char *);
/* /usr/include/stdlib.h:165:NC */ extern double strtod (const char *, char **);
/* /usr/include/stdlib.h:173:NC */ extern float strtof (const char *, char **);
/* /usr/include/stdlib.h:176:NC */ extern long double strtold (const char *, char **);
/* /usr/include/stdlib.h:184:NC */ extern long int strtol (const char *, char **, int);
/* /usr/include/stdlib.h:188:NC */ extern long unsigned int strtoul (const char *, char **, int);
/* /usr/include/stdlib.h:196:NC */ extern long long int strtoq (const char *, char **, int);
/* /usr/include/stdlib.h:201:NC */ extern long long unsigned int strtouq (const char *, char **, int);
/* /usr/include/stdlib.h:210:NC */ extern long long int strtoll (const char *, char **, int);
/* /usr/include/stdlib.h:215:NC */ extern long long unsigned int strtoull (const char *, char **, int);
/* /usr/include/stdlib.h:311:NC */ extern char *l64a (long int);
/* /usr/include/stdlib.h:314:NC */ extern long int a64l (const char *);
/* /usr/include/x86_64-linux-gnu/sys/select.h:107:NC */ extern int select (int, fd_set *, fd_set *, fd_set *, struct timeval *);
/* /usr/include/x86_64-linux-gnu/sys/select.h:119:NC */ extern int pselect (int, fd_set *, fd_set *, fd_set *, const struct timespec *, const __sigset_t *);
/* /usr/include/x86_64-linux-gnu/sys/sysmacros.h:33:NC */ extern unsigned int gnu_dev_major (long long unsigned int);
/* /usr/include/x86_64-linux-gnu/sys/sysmacros.h:36:NC */ extern unsigned int gnu_dev_minor (long long unsigned int);
/* /usr/include/x86_64-linux-gnu/sys/sysmacros.h:39:NC */ extern long long unsigned int gnu_dev_makedev (unsigned int, unsigned int);
/* /usr/include/stdlib.h:327:NC */ extern long int random (void);
/* /usr/include/stdlib.h:330:NC */ extern void srandom (unsigned int);
/* /usr/include/stdlib.h:336:NC */ extern char *initstate (unsigned int, char *, size_t);
/* /usr/include/stdlib.h:341:NC */ extern char *setstate (char *);
/* /usr/include/stdlib.h:360:NC */ extern int random_r (struct random_data *, int32_t *);
/* /usr/include/stdlib.h:363:NC */ extern int srandom_r (unsigned int, struct random_data *);
/* /usr/include/stdlib.h:366:NC */ extern int initstate_r (unsigned int, char *, size_t, struct random_data *);
/* /usr/include/stdlib.h:371:NC */ extern int setstate_r (char *, struct random_data *);
/* /usr/include/stdlib.h:380:NC */ extern int rand (void);
/* /usr/include/stdlib.h:382:NC */ extern void srand (unsigned int);
/* /usr/include/stdlib.h:387:NC */ extern int rand_r (unsigned int *);
/* /usr/include/stdlib.h:395:NC */ extern double drand48 (void);
/* /usr/include/stdlib.h:396:NC */ extern double erand48 (short unsigned int *);
/* /usr/include/stdlib.h:399:NC */ extern long int lrand48 (void);
/* /usr/include/stdlib.h:400:NC */ extern long int nrand48 (short unsigned int *);
/* /usr/include/stdlib.h:404:NC */ extern long int mrand48 (void);
/* /usr/include/stdlib.h:405:NC */ extern long int jrand48 (short unsigned int *);
/* /usr/include/stdlib.h:409:NC */ extern void srand48 (long int);
/* /usr/include/stdlib.h:410:NC */ extern short unsigned int *seed48 (short unsigned int *);
/* /usr/include/stdlib.h:412:NC */ extern void lcong48 (short unsigned int *);
/* /usr/include/stdlib.h:428:NC */ extern int drand48_r (struct drand48_data *, double *);
/* /usr/include/stdlib.h:430:NC */ extern int erand48_r (short unsigned int *, struct drand48_data *, double *);
/* /usr/include/stdlib.h:435:NC */ extern int lrand48_r (struct drand48_data *, long int *);
/* /usr/include/stdlib.h:438:NC */ extern int nrand48_r (short unsigned int *, struct drand48_data *, long int *);
/* /usr/include/stdlib.h:444:NC */ extern int mrand48_r (struct drand48_data *, long int *);
/* /usr/include/stdlib.h:447:NC */ extern int jrand48_r (short unsigned int *, struct drand48_data *, long int *);
/* /usr/include/stdlib.h:453:NC */ extern int srand48_r (long int, struct drand48_data *);
/* /usr/include/stdlib.h:456:NC */ extern int seed48_r (short unsigned int *, struct drand48_data *);
/* /usr/include/stdlib.h:459:NC */ extern int lcong48_r (short unsigned int *, struct drand48_data *);
/* /usr/include/stdlib.h:471:NC */ extern void *malloc (size_t);
/* /usr/include/stdlib.h:473:NC */ extern void *calloc (size_t, size_t);
/* /usr/include/stdlib.h:485:NC */ extern void *realloc (void *, size_t);
/* /usr/include/stdlib.h:488:NC */ extern void free (void *);
/* /usr/include/stdlib.h:493:NC */ extern void cfree (void *);
/* /usr/include/alloca.h:33:NC */ extern void *alloca (size_t);
/* /usr/include/stdlib.h:503:NC */ extern void *valloc (size_t);
/* /usr/include/stdlib.h:508:NC */ extern int posix_memalign (void **, size_t, size_t);
/* /usr/include/stdlib.h:514:NC */ extern void abort (void);
/* /usr/include/stdlib.h:518:NC */ extern int atexit (void (*) (void));
/* /usr/include/stdlib.h:536:NC */ extern int on_exit (void (*) (int, void *), void *);
/* /usr/include/stdlib.h:544:NC */ extern void exit (int);
/* /usr/include/stdlib.h:560:NC */ extern void _Exit (int);
/* /usr/include/stdlib.h:567:NC */ extern char *getenv (const char *);
/* /usr/include/stdlib.h:572:NC */ extern char *__secure_getenv (const char *);
/* /usr/include/stdlib.h:579:NC */ extern int putenv (char *);
/* /usr/include/stdlib.h:585:NC */ extern int setenv (const char *, const char *, int);
/* /usr/include/stdlib.h:589:NC */ extern int unsetenv (const char *);
/* /usr/include/stdlib.h:596:NC */ extern int clearenv (void);
/* /usr/include/stdlib.h:606:NC */ extern char *mktemp (char *);
/* /usr/include/stdlib.h:620:NC */ extern int mkstemp (char *);
/* /usr/include/stdlib.h:642:NC */ extern int mkstemps (char *, int);
/* /usr/include/stdlib.h:663:NC */ extern char *mkdtemp (char *);
/* /usr/include/stdlib.h:717:NC */ extern int system (const char *);
/* /usr/include/stdlib.h:734:NC */ extern char *realpath (const char *, char *);
/* /usr/include/stdlib.h:755:NC */ extern void *bsearch (const void *, const void *, size_t, size_t, __compar_fn_t);
/* /usr/include/stdlib.h:761:NC */ extern void qsort (void *, size_t, size_t, __compar_fn_t);
/* /usr/include/stdlib.h:771:NC */ extern int abs (int);
/* /usr/include/stdlib.h:772:NC */ extern long int labs (long int);
/* /usr/include/stdlib.h:776:NC */ extern long long int llabs (long long int);
/* /usr/include/stdlib.h:785:NC */ extern div_t div (int, int);
/* /usr/include/stdlib.h:787:NC */ extern ldiv_t ldiv (long int, long int);
/* /usr/include/stdlib.h:793:NC */ extern lldiv_t lldiv (long long int, long long int);
/* /usr/include/stdlib.h:808:NC */ extern char *ecvt (double, int, int *, int *);
/* /usr/include/stdlib.h:814:NC */ extern char *fcvt (double, int, int *, int *);
/* /usr/include/stdlib.h:820:NC */ extern char *gcvt (double, int, char *);
/* /usr/include/stdlib.h:826:NC */ extern char *qecvt (long double, int, int *, int *);
/* /usr/include/stdlib.h:829:NC */ extern char *qfcvt (long double, int, int *, int *);
/* /usr/include/stdlib.h:832:NC */ extern char *qgcvt (long double, int, char *);
/* /usr/include/stdlib.h:838:NC */ extern int ecvt_r (double, int, int *, int *, char *, size_t);
/* /usr/include/stdlib.h:841:NC */ extern int fcvt_r (double, int, int *, int *, char *, size_t);
/* /usr/include/stdlib.h:845:NC */ extern int qecvt_r (long double, int, int *, int *, char *, size_t);
/* /usr/include/stdlib.h:849:NC */ extern int qfcvt_r (long double, int, int *, int *, char *, size_t);
/* /usr/include/stdlib.h:860:NC */ extern int mblen (const char *, size_t);
/* /usr/include/stdlib.h:863:NC */ extern int mbtowc (wchar_t *, const char *, size_t);
/* /usr/include/stdlib.h:867:NC */ extern int wctomb (char *, wchar_t);
/* /usr/include/stdlib.h:871:NC */ extern size_t mbstowcs (wchar_t *, const char *, size_t);
/* /usr/include/stdlib.h:874:NC */ extern size_t wcstombs (char *, const wchar_t *, size_t);
/* /usr/include/stdlib.h:885:NC */ extern int rpmatch (const char *);
/* /usr/include/stdlib.h:896:NC */ extern int getsubopt (char **, char *const *, char **);
/* /usr/include/stdlib.h:948:NC */ extern int getloadavg (double *, int);
/* /usr/include/libio.h:418:NC */ extern int __underflow (_IO_FILE *);
/* /usr/include/libio.h:419:NC */ extern int __uflow (_IO_FILE *);
/* /usr/include/libio.h:420:NC */ extern int __overflow (_IO_FILE *, int);
/* /usr/include/libio.h:462:NC */ extern int _IO_getc (_IO_FILE *);
/* /usr/include/libio.h:463:NC */ extern int _IO_putc (int, _IO_FILE *);
/* /usr/include/libio.h:464:NC */ extern int _IO_feof (_IO_FILE *);
/* /usr/include/libio.h:465:NC */ extern int _IO_ferror (_IO_FILE *);
/* /usr/include/libio.h:467:NC */ extern int _IO_peekc_locked (_IO_FILE *);
/* /usr/include/libio.h:473:NC */ extern void _IO_flockfile (_IO_FILE *);
/* /usr/include/libio.h:474:NC */ extern void _IO_funlockfile (_IO_FILE *);
/* /usr/include/libio.h:475:NC */ extern int _IO_ftrylockfile (_IO_FILE *);
/* /usr/include/libio.h:492:NC */ extern int _IO_vfscanf (_IO_FILE *, const char *, __va_list_tag *, int *);
/* /usr/include/libio.h:494:NC */ extern int _IO_vfprintf (_IO_FILE *, const char *, __va_list_tag *);
/* /usr/include/libio.h:496:NC */ extern __ssize_t _IO_padn (_IO_FILE *, int, __ssize_t);
/* /usr/include/libio.h:497:NC */ extern size_t _IO_sgetn (_IO_FILE *, void *, size_t);
/* /usr/include/libio.h:499:NC */ extern __off64_t _IO_seekoff (_IO_FILE *, __off64_t, int, int);
/* /usr/include/libio.h:500:NC */ extern __off64_t _IO_seekpos (_IO_FILE *, __off64_t, int);
/* /usr/include/libio.h:502:NC */ extern void _IO_free_backup_area (_IO_FILE *);
/* /usr/include/stdio.h:179:NC */ extern int remove (const char *);
/* /usr/include/stdio.h:181:NC */ extern int rename (const char *, const char *);
/* /usr/include/stdio.h:186:NC */ extern int renameat (int, const char *, int, const char *);
/* /usr/include/stdio.h:196:NC */ extern FILE *tmpfile (void);
/* /usr/include/stdio.h:210:NC */ extern char *tmpnam (char *);
/* /usr/include/stdio.h:216:NC */ extern char *tmpnam_r (char *);
/* /usr/include/stdio.h:228:NC */ extern char *tempnam (const char *, const char *);
/* /usr/include/stdio.h:238:NC */ extern int fclose (FILE *);
/* /usr/include/stdio.h:243:NC */ extern int fflush (FILE *);
/* /usr/include/stdio.h:253:NC */ extern int fflush_unlocked (FILE *);
/* /usr/include/stdio.h:273:NC */ extern FILE *fopen (const char *, const char *);
/* /usr/include/stdio.h:279:NC */ extern FILE *freopen (const char *, const char *, FILE *);
/* /usr/include/stdio.h:307:NC */ extern FILE *fdopen (int, const char *);
/* /usr/include/stdio.h:320:NC */ extern FILE *fmemopen (void *, size_t, const char *);
/* /usr/include/stdio.h:326:NC */ extern FILE *open_memstream (char **, size_t *);
/* /usr/include/stdio.h:333:NC */ extern void setbuf (FILE *, char *);
/* /usr/include/stdio.h:337:NC */ extern int setvbuf (FILE *, char *, int, size_t);
/* /usr/include/stdio.h:344:NC */ extern void setbuffer (FILE *, char *, size_t);
/* /usr/include/stdio.h:348:NC */ extern void setlinebuf (FILE *);
/* /usr/include/stdio.h:357:NC */ extern int fprintf (FILE *, const char *, ...);
/* /usr/include/stdio.h:363:NC */ extern int printf (const char *, ...);
/* /usr/include/stdio.h:365:NC */ extern int sprintf (char *, const char *, ...);
/* /usr/include/stdio.h:372:NC */ extern int vfprintf (FILE *, const char *, __va_list_tag *);
/* /usr/include/stdio.h:378:NC */ extern int vprintf (const char *, __va_list_tag *);
/* /usr/include/stdio.h:380:NC */ extern int vsprintf (char *, const char *, __va_list_tag *);
/* /usr/include/stdio.h:387:NC */ extern int snprintf (char *, size_t, const char *, ...);
/* /usr/include/stdio.h:391:NC */ extern int vsnprintf (char *, size_t, const char *, __va_list_tag *);
/* /usr/include/stdio.h:418:NC */ extern int vdprintf (int, const char *, __va_list_tag *);
/* /usr/include/stdio.h:421:NC */ extern int dprintf (int, const char *, ...);
/* /usr/include/stdio.h:431:NC */ extern int fscanf (FILE *, const char *, ...);
/* /usr/include/stdio.h:437:NC */ extern int scanf (const char *, ...);
/* /usr/include/stdio.h:439:NC */ extern int sscanf (const char *, const char *, ...);
/* /usr/include/stdio.h:449:NC */ extern int fscanf (FILE *, const char *, ...);
/* /usr/include/stdio.h:452:NC */ extern int scanf (const char *, ...);
/* /usr/include/stdio.h:454:NC */ extern int sscanf (const char *, const char *, ...);
/* /usr/include/stdio.h:477:NC */ extern int vfscanf (FILE *, const char *, __va_list_tag *);
/* /usr/include/stdio.h:485:NC */ extern int vscanf (const char *, __va_list_tag *);
/* /usr/include/stdio.h:489:NC */ extern int vsscanf (const char *, const char *, __va_list_tag *);
/* /usr/include/stdio.h:500:NC */ extern int vfscanf (FILE *, const char *, __va_list_tag *);
/* /usr/include/stdio.h:505:NC */ extern int vscanf (const char *, __va_list_tag *);
/* /usr/include/stdio.h:508:NC */ extern int vsscanf (const char *, const char *, __va_list_tag *);
/* /usr/include/stdio.h:537:NC */ extern int fgetc (FILE *);
/* /usr/include/stdio.h:538:NC */ extern int getc (FILE *);
/* /usr/include/stdio.h:544:NC */ extern int getchar (void);
/* /usr/include/stdio.h:556:NC */ extern int getc_unlocked (FILE *);
/* /usr/include/stdio.h:557:NC */ extern int getchar_unlocked (void);
/* /usr/include/stdio.h:567:NC */ extern int fgetc_unlocked (FILE *);
/* /usr/include/stdio.h:579:NC */ extern int fputc (int, FILE *);
/* /usr/include/stdio.h:580:NC */ extern int putc (int, FILE *);
/* /usr/include/stdio.h:586:NC */ extern int putchar (int);
/* /usr/include/stdio.h:600:NC */ extern int fputc_unlocked (int, FILE *);
/* /usr/include/stdio.h:608:NC */ extern int putc_unlocked (int, FILE *);
/* /usr/include/stdio.h:609:NC */ extern int putchar_unlocked (int);
/* /usr/include/stdio.h:616:NC */ extern int getw (FILE *);
/* /usr/include/stdio.h:619:NC */ extern int putw (int, FILE *);
/* /usr/include/stdio.h:628:NC */ extern char *fgets (char *, int, FILE *);
/* /usr/include/stdio.h:636:NC */ extern char *gets (char *);
/* /usr/include/stdio.h:662:NC */ extern __ssize_t __getdelim (char **, size_t *, int, FILE *);
/* /usr/include/stdio.h:665:NC */ extern __ssize_t getdelim (char **, size_t *, int, FILE *);
/* /usr/include/stdio.h:675:NC */ extern __ssize_t getline (char **, size_t *, FILE *);
/* /usr/include/stdio.h:686:NC */ extern int fputs (const char *, FILE *);
/* /usr/include/stdio.h:692:NC */ extern int puts (const char *);
/* /usr/include/stdio.h:699:NC */ extern int ungetc (int, FILE *);
/* /usr/include/stdio.h:706:NC */ extern size_t fread (void *, size_t, size_t, FILE *);
/* /usr/include/stdio.h:712:NC */ extern size_t fwrite (const void *, size_t, size_t, FILE *);
/* /usr/include/stdio.h:734:NC */ extern size_t fread_unlocked (void *, size_t, size_t, FILE *);
/* /usr/include/stdio.h:736:NC */ extern size_t fwrite_unlocked (const void *, size_t, size_t, FILE *);
/* /usr/include/stdio.h:746:NC */ extern int fseek (FILE *, long int, int);
/* /usr/include/stdio.h:751:NC */ extern long int ftell (FILE *);
/* /usr/include/stdio.h:756:NC */ extern void rewind (FILE *);
/* /usr/include/stdio.h:770:NC */ extern int fseeko (FILE *, __off_t, int);
/* /usr/include/stdio.h:775:NC */ extern __off_t ftello (FILE *);
/* /usr/include/stdio.h:795:NC */ extern int fgetpos (FILE *, fpos_t *);
/* /usr/include/stdio.h:800:NC */ extern int fsetpos (FILE *, const fpos_t *);
/* /usr/include/stdio.h:823:NC */ extern void clearerr (FILE *);
/* /usr/include/stdio.h:825:NC */ extern int feof (FILE *);
/* /usr/include/stdio.h:827:NC */ extern int ferror (FILE *);
/* /usr/include/stdio.h:832:NC */ extern void clearerr_unlocked (FILE *);
/* /usr/include/stdio.h:833:NC */ extern int feof_unlocked (FILE *);
/* /usr/include/stdio.h:834:NC */ extern int ferror_unlocked (FILE *);
/* /usr/include/stdio.h:843:NC */ extern void perror (const char *);
/* /usr/include/stdio.h:855:NC */ extern int fileno (FILE *);
/* /usr/include/stdio.h:860:NC */ extern int fileno_unlocked (FILE *);
/* /usr/include/stdio.h:870:NC */ extern FILE *popen (const char *, const char *);
/* /usr/include/stdio.h:876:NC */ extern int pclose (FILE *);
/* /usr/include/stdio.h:882:NC */ extern char *ctermid (char *);
/* /usr/include/stdio.h:910:NC */ extern void flockfile (FILE *);
/* /usr/include/stdio.h:914:NC */ extern int ftrylockfile (FILE *);
/* /usr/include/stdio.h:917:NC */ extern void funlockfile (FILE *);
/* /usr/include/string.h:44:NC */ extern void *memcpy (void *, const void *, size_t);
/* /usr/include/string.h:49:NC */ extern void *memmove (void *, const void *, size_t);
/* /usr/include/string.h:57:NC */ extern void *memccpy (void *, const void *, int, size_t);
/* /usr/include/string.h:65:NC */ extern void *memset (void *, int, size_t);
/* /usr/include/string.h:68:NC */ extern int memcmp (const void *, const void *, size_t);
/* /usr/include/string.h:95:NC */ extern void *memchr (const void *, int, size_t);
/* /usr/include/string.h:128:NC */ extern char *strcpy (char *, const char *);
/* /usr/include/string.h:131:NC */ extern char *strncpy (char *, const char *, size_t);
/* /usr/include/string.h:136:NC */ extern char *strcat (char *, const char *);
/* /usr/include/string.h:139:NC */ extern char *strncat (char *, const char *, size_t);
/* /usr/include/string.h:143:NC */ extern int strcmp (const char *, const char *);
/* /usr/include/string.h:146:NC */ extern int strncmp (const char *, const char *, size_t);
/* /usr/include/string.h:150:NC */ extern int strcoll (const char *, const char *);
/* /usr/include/string.h:153:NC */ extern size_t strxfrm (char *, const char *, size_t);
/* /usr/include/string.h:165:NC */ extern int strcoll_l (const char *, const char *, __locale_t);
/* /usr/include/string.h:168:NC */ extern size_t strxfrm_l (char *, const char *, size_t, __locale_t);
/* /usr/include/string.h:175:NC */ extern char *strdup (const char *);
/* /usr/include/string.h:183:NC */ extern char *strndup (const char *, size_t);
/* /usr/include/string.h:235:NC */ extern char *strchr (const char *, int);
/* /usr/include/string.h:262:NC */ extern char *strrchr (const char *, int);
/* /usr/include/string.h:284:NC */ extern size_t strcspn (const char *, const char *);
/* /usr/include/string.h:288:NC */ extern size_t strspn (const char *, const char *);
/* /usr/include/string.h:314:NC */ extern char *strpbrk (const char *, const char *);
/* /usr/include/string.h:342:NC */ extern char *strstr (const char *, const char *);
/* /usr/include/string.h:348:NC */ extern char *strtok (char *, const char *);
/* /usr/include/string.h:354:NC */ extern char *__strtok_r (char *, const char *, char **);
/* /usr/include/string.h:359:NC */ extern char *strtok_r (char *, const char *, char **);
/* /usr/include/string.h:399:NC */ extern size_t strlen (const char *);
/* /usr/include/string.h:406:NC */ extern size_t strnlen (const char *, size_t);
/* /usr/include/string.h:413:NC */ extern char *strerror (int);
/* /usr/include/string.h:427:NC */ extern int strerror_r (int, char *, size_t);
/* /usr/include/string.h:445:NC */ extern char *strerror_l (int, __locale_t);
/* /usr/include/string.h:451:NC */ extern void __bzero (void *, size_t);
/* /usr/include/string.h:455:NC */ extern void bcopy (const void *, void *, size_t);
/* /usr/include/string.h:459:NC */ extern void bzero (void *, size_t);
/* /usr/include/string.h:462:NC */ extern int bcmp (const void *, const void *, size_t);
/* /usr/include/string.h:489:NC */ extern char *index (const char *, int);
/* /usr/include/string.h:517:NC */ extern char *rindex (const char *, int);
/* /usr/include/string.h:523:NC */ extern int ffs (int);
/* /usr/include/string.h:536:NC */ extern int strcasecmp (const char *, const char *);
/* /usr/include/string.h:540:NC */ extern int strncasecmp (const char *, const char *, size_t);
/* /usr/include/string.h:559:NC */ extern char *strsep (char **, const char *);
/* /usr/include/string.h:566:NC */ extern char *strsignal (int);
/* /usr/include/string.h:569:NC */ extern char *__stpcpy (char *, const char *);
/* /usr/include/string.h:571:NC */ extern char *stpcpy (char *, const char *);
/* /usr/include/string.h:576:NC */ extern char *__stpncpy (char *, const char *, size_t);
/* /usr/include/string.h:579:NC */ extern char *stpncpy (char *, const char *, size_t);
/* /usr/include/malloc.h:61:NC */ extern void *malloc (size_t);
/* /usr/include/malloc.h:64:NC */ extern void *calloc (size_t, size_t);
/* /usr/include/malloc.h:72:NC */ extern void *realloc (void *, size_t);
/* /usr/include/malloc.h:76:NC */ extern void free (void *);
/* /usr/include/malloc.h:79:NC */ extern void cfree (void *);
/* /usr/include/malloc.h:82:NC */ extern void *memalign (size_t, size_t);
/* /usr/include/malloc.h:86:NC */ extern void *valloc (size_t);
/* /usr/include/malloc.h:90:NC */ extern void *pvalloc (size_t);
/* /usr/include/malloc.h:97:NC */ extern void *__default_morecore (ptrdiff_t);
/* /usr/include/malloc.h:117:NC */ extern struct mallinfo mallinfo (void);
/* /usr/include/malloc.h:144:NC */ extern int mallopt (int, int);
/* /usr/include/malloc.h:148:NC */ extern int malloc_trim (size_t);
/* /usr/include/malloc.h:152:NC */ extern size_t malloc_usable_size (void *);
/* /usr/include/malloc.h:155:NC */ extern void malloc_stats (void);
/* /usr/include/malloc.h:158:NC */ extern int malloc_info (int, FILE *);
/* /usr/include/malloc.h:161:NC */ extern void *malloc_get_state (void);
/* /usr/include/malloc.h:165:NC */ extern int malloc_set_state (void *);
/* /usr/include/malloc.h:190:NC */ extern void __malloc_check_init (void);
/* test.c:18:NF */ extern int myffs (long unsigned int data); /* (data) long unsigned int data; */
/* test.c:42:NF */ extern int try (int a, int b, int c); /* (a, b, c) int a; int b; int c; */
/* test.c:47:NF */ extern void myfree (void *p); /* (p) void *p; */
/* test.c:51:NF */ extern int main (void); /* () */
