#
# (C) COPYRIGHT ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

video-tx-y += video_tx.o
obj-$(CONFIG_VIDEO_TX) += video-tx.o

test-video-tx-y += test_video_tx.o
obj-$(CONFIG_TEST_VIDEO_TX) += test-video-tx.o

obj-$(CONFIG_SII902X) += sii902x.o

obj-$(CONFIG_SENC_TX) += senc_tx.o
