C_DEFINES +=

ASM_LIST +=

C_LIST += bl-vop.c
C_LIST += vop_config_blob_parser.c
C_LIST += rk_disp.c
C_LIST += rk_vop.c
C_LIST += nano_lvds.c
C_LIST += dsi_display.c
C_LIST += dsi_hwregs.c

SOURCEDIR += $(SOCDIR)/devices/vop/src
SOURCEDIR += $(SOCDIR)/devices/vop/src/sofia3gr

INCLUDEDIR += $(SOCDIR)/devices/dcc/inc
